### PR TITLE
Add quarkus-super-heroes to status page

### PR DESCRIPTION
**Pull request by edeandrea**
Add quarkus-super-heroes (quarkusio/quarkus#23612) to the main status page

### CODE REVIEW

**Comment by edeandrea** [comment]
Hi @gsmet any chance of getting this merged?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
That's what you get for creating PRs during my PTOs :).

**Comment by edeandrea** [comment]
Ahh sorry I wasn't aware you were on PTO! Thank you for taking care of it!

**Comment by gsmet** [comment]
I just deployed the new version so we're all set.

**Comment by gsmet** [comment]
I'm back from PTO, I just missed the initial notification so good call to mention it to me!

**Pull request merged**
